[package]
name = "mm_multi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.0.3"
num = "0.2.0"
clap = "2.33.0"
num_cpus = "1.10.0"
crossbeam = "0.7.1"
rand = "0.8.5"
